### ISSUE TITLE
fix trending component's font-size, gap and margins on mobile screen size to make it responsive

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#110]

**Comment by jsvigneshkanna** [comment]
Assign me this issue, will fix this in sometime

**Comment by gaurav-iitb** [comment]
can you please assign this to me

**Comment by Aadarsh805** [comment]
> Assign me this issue, will fix this in sometime

alright you have this, don't take much time though or we'll assign the next user

**Comment by Aadarsh805** [comment]
> can you please assign this to me

I'll create some other issue for you

**Comment by gaurav-iitb** [comment]
sure thanks
