### ISSUE TITLE
remove music,podcast, live links from navbar component on  mobile screen size as well as the settings icon

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#111]
we can maybe create a dropdown fro music, podcast and live later

**Comment by Aadarsh805** [comment]
![Screenshot from 2022-10-10 23-57-37](https://user-images.githubusercontent.com/95094057/194930934-eb479c5a-8354-4ada-9fa0-4f8ecb2e2f54.png)

**Comment by gaurav-iitb** [comment]
please assign this to me

**Comment by Aman-Mandal** [comment]
> please assign this to me

I've already assigned you a task...so if you wanna do this one too!! Lemme know

**Comment by gaurav-iitb** [comment]
yeah please assign me this one too

**Comment by Aman-Mandal** [comment]
> yeah please assign me this one too

Okayy... fix both the issues on same branch and make only 1 PR

**Comment by gaurav-iitb** [comment]
@Aman-Mandal hi I have merged the pr please review it
ThankYou!!
