### ISSUE TITLE
fix overflow form the floating player component on small mobile sizes

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#112]
make icons small, remove left padding and make it fit nicely
![Screenshot from 2022-10-11 00-01-15](https://user-images.githubusercontent.com/95094057/194931254-9026022e-704a-45a6-ad57-069c643fcb44.png)

**Comment by gaurav-iitb** [comment]
please assign this to me

**Comment by Aman-Mandal** [comment]
> please assign this to me

Good luck
