### ISSUE TITLE
fix overall left padding on this screen size, iphone 12pro(390x844)

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#113]
![Screenshot from 2022-10-11 00-04-35](https://user-images.githubusercontent.com/95094057/194931683-4a55497c-128a-4772-8e73-c8e7e5804ec6.png)

**Comment by ankitkumar0622** [comment]
hi , can you please assign me this task.

**Comment by Aman-Mandal** [comment]
> hi , can you please assign me this task.
> 

Go ahead Sir
