### ISSUE TITLE
[Bug] The time duration shows NaN

### ISSUE THREAD

**Issue by ann0nip** [Aman-Mandal/groovy#115]
At the beginning of the song loading, the song duration in the player shows NaN.

I can fix this. Please assign the issue to me. 

<img width="732" alt="Screen Shot 2022-10-11 at 11 46 13" src="https://user-images.githubusercontent.com/2248100/195125915-1dec03e9-4811-4c79-9de6-86b03f06418b.png">

**Comment by Aman-Mandal** [comment]
Thanks for giving your time ✨
