### ISSUE TITLE
Sidebar Title  

### ISSUE THREAD

**Issue by Rohan-Hazari** [Aman-Mandal/groovy#130]
The sidebar title is placed weirdly and also missing the icon

![image](https://user-images.githubusercontent.com/91898040/195670519-0f893b1e-db70-4ef9-a14e-a7991e747460.png)

![image](https://user-images.githubusercontent.com/91898040/195666747-af32f685-434a-44f2-8c2f-85c2e1ff9978.png)

Don't assign it to me just wanted to point out 
This can be a good first issue for newcomers :)

**Comment by Aman-Mandal** [comment]
Thanks for pointing it out
