### ISSUE TITLE
[BUG] The Icons on the Navbar got transparent

### ISSUE THREAD

**Issue by Aman-Mandal** [Aman-Mandal/groovy#134]
All the icons on the Navbar got transparent or black 
![image](https://user-images.githubusercontent.com/64729135/195776095-1fa52959-9091-4374-8b07-2247f49f24cb.png)

Make it look like the Original UI

**Comment by Anish-Sarawgi** [comment]
@Aman-Mandal  I want to work on this issue.

**Comment by jsvigneshkanna** [comment]
Please assign me this issue, will fix

**Comment by Aman-Mandal** [comment]
> @Aman-Mandal I want to work on this issue.

Go ahead Sir :))

**Comment by Aman-Mandal** [comment]
> Please assign me this issue, will fix

Hey, sorry mate!! But @Anish-Sarawgi asked first, and you can check out other issues in the repo!! I hope you will find a nice one

**Comment by Aman-Mandal** [comment]
Any updates @Anish-Sarawgi ?
