### ISSUE TITLE
[Feature] Add a Close button on Sidebar in mobile size

### ISSUE THREAD

**Issue by Aman-Mandal** [Aman-Mandal/groovy#135]
There's no way to close the Sidebar on the small screen (Mobile)
![image](https://user-images.githubusercontent.com/64729135/195776675-8900cab6-3afc-4270-a2d2-d71beedcca8a.png)

So add a close button to the sidebar along side the Groovy logo

**Comment by jsvigneshkanna** [comment]
Please assign me this issue

**Comment by Aman-Mandal** [comment]
Sure @jsvigneshkanna !! Go ahead

**Comment by sandilya27** [comment]
can I work on this issue?

**Comment by Aman-Mandal** [comment]
> can I work on this issue?

it's already assigned to someone Sir
