### ISSUE TITLE
make genre page navlist (tablist), linked to their dynamic Genre/[genreCategory]

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#137]
![image](https://user-images.githubusercontent.com/95094057/195856304-ab3ba9dd-d163-41ac-9848-eb5cd7f8fe95.png)

**Comment by simonkrizo** [comment]
Hello, I would like to contribute, can you assign this issue to me?

**Comment by sumit-022** [comment]
I can work on this. Please assign this to me

**Comment by jankvc** [comment]
I can do this, assign me please

**Comment by Aman-Mandal** [comment]
> I can work on this. Please assign this to me

Here u go!!🤜🤛

**Comment by Aman-Mandal** [comment]
> I can do this, assign me please

Hey man, sorry but @sumit-022 asked first!! You can checkout others issues

**Comment by jankvc** [comment]
can u assign me, since he removed himself

**Comment by Aman-Mandal** [comment]
> can u assign me, since he removed himself

go ahead
