### ISSUE TITLE
[BUG] Add the key prop 

### ISSUE THREAD

**Issue by Aman-Mandal** [Aman-Mandal/groovy#142]
![IMG_20221016_124438.jpg](https://user-images.githubusercontent.com/64729135/196023292-d6fcf538-a58e-41c5-aec3-150e6cbfc667.jpg)

Add the key prop in TopArtist.jsx component, its giving trouble while deployment!!

**Comment by jason1985** [comment]
I'd like to do this one if possible

**Comment by Aman-Mandal** [comment]
> I'd like to do this one if possible

Sure...go ahead Sir!!

Assigned you

**Comment by Aman-Mandal** [comment]
Thanks @jason1985
