### ISSUE TITLE
Fix icon colours 

### ISSUE THREAD

**Issue by MunavvarSinan** [Aman-Mandal/groovy#151]
All the icons like notification , hamburger etc are in just black and it is not visible

**Comment by andrewkykoo** [comment]
Hi @MunavvarSinan @Aman-Mandal, do we have any expectations in terms of colors? If not, I can go head and update the icons with most suitable colors.

**Comment by Aman-Mandal** [comment]
> Hi @MunavvarSinan @Aman-Mandal, do we have any expectations in terms of colors? If not, I can go head and update the icons with most suitable colors.

No expectations as of now, just simply make it off-white

**Comment by andrewkykoo** [comment]
> > Hi @MunavvarSinan @Aman-Mandal, do we have any expectations in terms of colors? If not, I can go head and update the icons with most suitable colors.
> 
> No expectations as of now, just simply make it off-white

Which icons are you referring to? A screenshot of them could help. What I am seeing on the landing page are already white notification button and hamburger menu icon.

**Comment by MunavvarSinan** [comment]
![Screenshot_20221025-111040-489~2.png](https://user-images.githubusercontent.com/73233808/197691930-680b020b-e689-44fd-b9b9-34731a777840.png)

**Comment by Aadarsh805** [comment]
> ![Screenshot_20221025-111040-489~2.png](https://user-images.githubusercontent.com/73233808/197691930-680b020b-e689-44fd-b9b9-34731a777840.png)

These were already fixed, you sure your repo is on sync??

**Comment by MunavvarSinan** [comment]
It was not fixed when i was reported this issue

**Comment by Aadarsh805** [comment]
> It was not fixed when i was reported this issue

it works on mine
