### ISSUE TITLE
The sidebar should close when a sidebar link is clicked on mobile screen size

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#153]

**Comment by srijoy-paul** [comment]
Hey @Aadarsh805 I would like to work on this, assign me this

**Comment by Aadarsh805** [comment]
> Hey @Aadarsh805 I would like to work on this, assign me this

u have it, go ahead

**Comment by Aadarsh805** [comment]
this has already been solved

**Comment by srijoy-paul** [comment]
If there is no, rules on your repo, then why do you even added hactoberfest label, just to time waste of people.
If this was an open issue, and commented to assign by someone.
then how it can be solved by others. And even you are accepting
