### ISSUE TITLE
Add key property to list items in GenreNav component to fix build error

### ISSUE THREAD

**Issue by ashleymays** [Aman-Mandal/groovy#155]
When attempting to build, ESLint gave the following error:

> Error: Missing "key" prop for element in iterator  react/jsx-key

This prevents the project from being built. I'd like to add the `key` property to the list to fix it, probably to make the category name the key.

**Comment by Aadarsh805** [comment]
> When attempting to build, ESLint gave the following error:
> 
> > Error: Missing "key" prop for element in iterator  react/jsx-key
> 
> This prevents the project from being built. I'd like to add the `key` property to the list to fix it, probably to make the category name the key.

This project is not being maintained or even used right now
So might be a time-wasting thing to do
but if you still wanna do it, go ahead
I'll make sure to review your pr and merge it
