### ISSUE TITLE
[Enhancement] make navbar responsive

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#24]

**Comment by Im-Kunal-13** [comment]
@Aadarsh805 I would like to work on this issue. Can you assign this to me?

**Comment by Aman-Mandal** [comment]
> @Aadarsh805 I would like to work on this issue. Can you assign this to me?

Go ahead Ser !!

**Comment by Aadarsh805** [comment]
@Aman-Mandal bro how we gonna keep navbar on mobile, do we make another onclick sidebar or do we just push those links to the already made sidebar or we just make then small

**Comment by hamzailyas237** [comment]
I want to contribute please assign it to me

**Comment by Aadarsh805** [comment]
lets just make them small for now, we'll do it later

**Comment by Aadarsh805** [comment]
> I want to contribute please assign it to me

it's already assigned, you can try other issues or just wait 2-3 days if we don't get any response from the assignee, we'll assign it to you

**Comment by Im-Kunal-13** [comment]
I'm on it.

> > I want to contribute please assign it to me
> 
> it's already assigned, you can try other issues or just wait 2-3 days if we don't get any response from the assignee, we'll assign it to you

**Comment by Aman-Mandal** [comment]
> @Aman-Mandal bro how we gonna keep navbar on mobile, do we make another onclick sidebar or do we just push those links to the already made sidebar or we just make then small

We can simply add the navbar links on our already present sidebar and hide the navbar on small screens

**Comment by Aadarsh805** [comment]
> I'm on it.
> 
> > > I want to contribute please assign it to me
> > 
> > 
> > it's already assigned, you can try other issues or just wait 2-3 days if we don't get any response from the assignee, we'll assign it to you

alright Kunal, go ahead

**Comment by Im-Kunal-13** [comment]
> > I'm on it.
> > > > I want to contribute please assign it to me
> > > 
> > > 
> > > it's already assigned, you can try other issues or just wait 2-3 days if we don't get any response from the assignee, we'll assign it to you
> 
> alright Kunal, go ahead

Is there a discord community or something where I can contact if I get some issues while developing?

**Comment by Aadarsh805** [comment]
> > > I'm on it.
> > > > > I want to contribute please assign it to me
> > > > 
> > > > 
> > > > it's already assigned, you can try other issues or just wait 2-3 days if we don't get any response from the assignee, we'll assign it to you
> > 
> > 
> > alright Kunal, go ahead
> 
> Is there a discord community or something where I can contact if I get some issues while developing?

@Aman-Mandal where should they contact us

**Comment by Aman-Mandal** [comment]
We don't have a community yet, you can text us on twitter (given on readme) for now!! Will make a group/channel soon ✨

**Comment by Im-Kunal-13** [comment]
> We don't have a community yet, you can text us on twitter (given on readme) for now!! Will make a group/channel soon ✨

Cool
