### ISSUE TITLE
[Feature] Make top artists and other sections on explore page responsive using overflow scroll and add scroll buttons too

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#25]

**Comment by PrajwalDhule** [comment]
can I also work on this issue simultaneously or do I need to complete a previously assigned issue first?

**Comment by Aman-Mandal** [comment]
You wanna do it together? If yess you can.. just give a heads up here

**Comment by PrajwalDhule** [comment]
I had a doubt, what is the purpose of scroll buttons here, is it just to indicate you can scroll down? And do you want just one (for the whole page)?

Actually we are using dummy data for now right? But once we integrate it with API we will need the scroll thing 

What do u say?

**Comment by Aadarsh805** [comment]
> I had a doubt, what is the purpose of scroll buttons here, is it just to indicate you can scroll down? And do you want just one (for the whole page)?

umm it's for mobile screen as 7-8 artists won't fit in mobile screen so we will make them scrollable and have those hover buttons that you can also scroll using buttons if u don't wanna use shift + scroll just like in Netflix browse section they have scrollable rows

**Comment by Aadarsh805** [comment]
top artists is done but still need to do top charts as it is overflowing out of screen

**Comment by Aadarsh805** [comment]
this is also done
