### ISSUE TITLE
make trending new hits section scrollable, use dummy data and also make it dynamic

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#26]

**Comment by PrajwalDhule** [comment]
I would like to work on this, can you assign it to me?

**Comment by Aman-Mandal** [comment]
> I would like to work on this, can you assign it to me?

Sure Prajwal..go ahead!! Make sure you create a new branch 😃

**Comment by PrajwalDhule** [comment]
Hey, just wanted to ask what exactly do you mean by making the new hits section scrollable?

**Comment by Aadarsh805** [comment]
> Hey, just wanted to ask what exactly do you mean by making the new hits section scrollable?

you see on the right side of trending section there are buttons and pagination kinda thing to change the trending among 4-5 trending songs, that thing

![image_processing20200424-21471-1174txc (1)](https://user-images.githubusercontent.com/95094057/194147199-3547c50e-141a-4318-a5fc-c003f5048067.png)

**Comment by Aman-Mandal** [comment]
> Hey, just wanted to ask what exactly do you mean by making the new hits section scrollable?

Make a carousel for 4-5 songs (dummy data) and by clicking on the buttons they should change eg. Image slider in our gallery

**Comment by Aadarsh805** [comment]
@PrajwalDhule aif you working on this, you dont have to make the whole thing, the component is already made but wasn't imported in explore page so I just did that, u can take a pull and then work on just the carousel thing

**Comment by PrajwalDhule** [comment]
> @PrajwalDhule aif you working on this, you dont have to make the whole thing, the component is already made but wasn't imported in explore page so I just did that, u can take a pull and then work on just the carousel thing

ok cool got it, thanks
