### ISSUE TITLE
Make top charts component, very similar to top artists and groovy component, copy/paste

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#28]

**Comment by hamzailyas237** [comment]
I want to work on this please assign this issue to me.

**Comment by Aman-Mandal** [comment]
> I want to work on this please assign this issue to me.

Go ahead ..a

**Comment by Aman-Mandal** [comment]
> I want to work on this please assign this issue to me.

Go ahead!! And a very good luck

**Comment by hamzailyas237** [comment]
Thankyou.

**Comment by hamzailyas237** [comment]
I want to ask what content I can add to the top charts component. Please give some description.

**Comment by Aadarsh805** [comment]
> I want to ask what content I can add to the top charts component. Please give some description.

use the same data as in the UI
![image_processing20200424-21471-1174txc (1)](https://user-images.githubusercontent.com/95094057/194137700-8b6e31ca-61de-4bd4-9579-fb8881269053.png)

**Comment by hamzailyas237** [comment]
@Aman-Mandal okay

**Comment by Aadarsh805** [comment]
done
