### ISSUE TITLE
Typo Error

### ISSUE THREAD

**Issue by Rohan-Hazari** [Aman-Mandal/groovy#29]
Shows this error when loading
![image](https://user-images.githubusercontent.com/91898040/194132276-4463fdb8-f0be-4dba-aba9-4de46567d199.png)

In components/Navbar/Navbar.jsx line 42

Changing it to
window.removeEventListener("resize", handleResize);
fixes this 

I am new to next.js sorry if this is some mistake from my side while setting up the project locally

**Comment by Aadarsh805** [comment]
> Shows this error when loading ![image](https://user-images.githubusercontent.com/91898040/194132276-4463fdb8-f0be-4dba-aba9-4de46567d199.png)
> 
> In components/Navbar/Navbar.jsx line 42
> 
> Changing it to window.removeEventListener("resize", handleResize); fixes this
> 
> I am new to next.js sorry if this is some mistake from my side while setting up the project locally

nah nah it's a typo, you can change it

**Comment by Aman-Mandal** [comment]
> Shows this error when loading
> ![image](https://user-images.githubusercontent.com/91898040/194132276-4463fdb8-f0be-4dba-aba9-4de46567d199.png)
> 
> In components/Navbar/Navbar.jsx line 42
> 
> Changing it to
> window.removeEventListener("resize", handleResize);
> fixes this 
> 
> I am new to next.js sorry if this is some mistake from my side while setting up the project locally

No worries..you wanna fix this? If yess go ahead and make a PR

**Comment by Rohan-Hazari** [comment]
Sure I will make a PR 
Thanks
