### ISSUE TITLE
[Fix] Fix the height of whole application

### ISSUE THREAD

**Issue by Aman-Mandal** [Aman-Mandal/groovy#39]
Right now as you can see the height of the application keeps on increasing as we add more data, but it should be fixed!! 

![image](https://user-images.githubusercontent.com/64729135/194213116-eddbb8c7-c4c5-4a31-8edb-3809f08bf86c.png)

**Comment by najeebkp** [comment]
hi @Aman-Mandal  please assign this to me

**Comment by Aman-Mandal** [comment]
Good luck @najeebkp
