### ISSUE TITLE
move navbar links to sidebar when on mobile view

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#42]
we can keep the notification and settings in nav on the right side , moving others to sidebar

**Comment by Aadarsh805** [comment]
we can keep the notification and settings in nav on the right side , moving others to sidebar

**Comment by Soumyajit2825** [comment]
@Aadarsh805 want to contribute in it

**Comment by Aadarsh805** [comment]
@Soumyajit2825 alright go ahead and good luck

**Comment by Soumyajit2825** [comment]
ok thanks

**Comment by Aadarsh805** [comment]
@Soumyajit2825 what you can do this make the same search from navbar on sidebar top after the grooy logo and keep it hidden until screen size less than md
you can just hide profile and other links on mobile for now

**Comment by Soumyajit2825** [comment]
ohkay trying to do as u told

**Comment by Soumyajit2825** [comment]
@Aadarsh805 I thought that it is based on HTML but looks like react-js.

**Comment by Aadarsh805** [comment]
@Soumyajit2825 yeah it's react + next, you are not familiar with react ig, no worries

**Comment by Soumyajit2825** [comment]
yes...thanks

**Comment by peterintech** [comment]
please assign this to me

**Comment by Aman-Mandal** [comment]
> please assign this to me

Suree...go ahead Sir!!

**Comment by peterintech** [comment]
Alright, let me keep my self busy

**Comment by peterintech** [comment]
DO you have the designs

**Comment by Aman-Mandal** [comment]
> DO you have the designs

Naah .. we dont have designs right now !!

**Comment by peterintech** [comment]
Alright, I'll create one.
I'll also add a floating player menu link this
![ApplicationFrameHost_hILa0g3snN](https://user-images.githubusercontent.com/66377818/194678680-32ad78ff-b02e-4f90-9f01-4a0b0e43ed93.png)

**Comment by Aadarsh805** [comment]
> Alright, I'll create one. I'll also add a floating player menu link this ![ApplicationFrameHost_hILa0g3snN](https://user-images.githubusercontent.com/66377818/194678680-32ad78ff-b02e-4f90-9f01-4a0b0e43ed93.png)

that'd be awesome
