### ISSUE TITLE
[UI/UX] Create a UI Design for 'Genres' page

### ISSUE THREAD

**Issue by Aman-Mandal** [Aman-Mandal/groovy#46]
Create a figma file for Genres page, make sure it looks similar to the Homepage(Explore page).

Steps :

1. Fork and clone it
2. Install dependencies
3. Open the Design folder
4. Create a new sub-folder called "Desktop-Genres_page"
5. Add a Figma/image file of the design u created
6. Push it and create a PR

**Comment by ARNAV1233** [comment]
@Aman-Mandal  can I do it

**Comment by Aman-Mandal** [comment]
> @Aman-Mandal can I do it

Yess Sir ...go ahead

Make sure u create a new branch

**Comment by Aman-Mandal** [comment]
I have added the design folder, add the figma file inside it

**Comment by ARNAV1233** [comment]
thanks

**Comment by 72002sweta** [comment]
i would like to contribute will you please assign me this.

**Comment by Aman-Mandal** [comment]
> i would like to contribute will you please assign me this.

Go ahead✨

**Comment by 72002sweta** [comment]
done @Aman-Mandal please check

**Comment by Aman-Mandal** [comment]
> done @Aman-Mandal please check
> 

Nice one!!🤞
