### ISSUE TITLE
the searchbar disturbs the position of navbar when something is searched, the search box should be out of input field and below the input search

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#55]
![Screenshot from 2022-10-06 17-49-39](https://user-images.githubusercontent.com/95094057/194310891-f8333a74-38f1-4e3e-8fd0-f10e9e425c81.png)

**Comment by manav-06** [comment]
Hi @Aadarsh805 You can assign this to me

**Comment by Aadarsh805** [comment]
@manav-06 yep go ahead Manav
