### ISSUE TITLE
Navbar bugs, minor UI fixes and removal of unused code.

### ISSUE THREAD

**Issue by tarunfy** [Aman-Mandal/groovy#56]
Found a bug in the navbar and had to fix search bar width in the navbar for better UX.
<img width="1440" alt="Screenshot 2022-10-06 at 7 04 01 PM" src="https://user-images.githubusercontent.com/51208270/194327376-a727cf9e-167e-44c8-ae30-0c1c4e9aa0e0.png">

It says 'none' in the navbar even when there's no user for profile picture. Please assign me this task to fix all these issues 🙂

**Comment by Aadarsh805** [comment]
@tarunfy did u push those changes ??
also u need to make a git pull after you sync your forked repo, this is 2-3 commits behind ig

**Comment by Aman-Mandal** [comment]
#59
