### ISSUE TITLE
[BUG] Fix the notification modal and close modal by clicking the notification button

### ISSUE THREAD

**Issue by Aman-Mandal** [Aman-Mandal/groovy#62]
(Issue for beginners)

1. Fix the notification modal by adding the z-index property
2. When the notification button is clicked, the modal should close!!

![image](https://user-images.githubusercontent.com/64729135/194389222-ea71342d-634e-459c-b9ee-6fcc739c9933.png)

**Comment by racky7** [comment]
@Aman-Mandal Please assign it to me.

**Comment by Aman-Mandal** [comment]
> @Aman-Mandal Please assign it to me.

Go ahead Sir..good luck!!

**Comment by Aadarsh805** [comment]
@Aman-Mandal is there scroll still in your screen size
or is your cloned repo behind some commits, because this issue is already fixed

**Comment by Aman-Mandal** [comment]
> @Aman-Mandal is there scroll still in your screen size or is your cloned repo behind some commits, because this issue is already fixed

Are u sure? because my repo is totally updated...maybe someone fixed it after putting the issue
Coz, it was there last night

**Comment by Aadarsh805** [comment]
yeah maybe, it works fine now in mine, you can also check in your local

**Comment by Aadarsh805** [comment]
this is fixed
