### ISSUE TITLE
fix search functionality to filter songs starting from that letter and not all letters present in that song 

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#65]
like if you put 'a' in the input field it should show songs starting from 'a' only and not all songs containing 'a' in it

**Comment by shivampandey0** [comment]
Hi, I can fix it. Can you assign it to me?

**Comment by Aadarsh805** [comment]
> Hi, I can fix it. Can you assign it to me?

great, go ahead

**Comment by shivampandey0** [comment]
PR #73 fixes this
