### ISSUE TITLE
add dummy songs with trending songs data, top charts data and push them into player and autoplay

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#69]

**Comment by chakrinya009** [comment]
can you please assign this issue

**Comment by OneAutumLeaf** [comment]
hi  @Aadarsh805 
can u please assign this to me

**Comment by Aadarsh805** [comment]
> hi @Aadarsh805 can u please assign this to me

assigned, good luck

**Comment by Aadarsh805** [comment]
no wait @chakrinya009 asked first so they get it
