### ISSUE TITLE
make cursor to pointer when hovering Groovy title in sidebar

### ISSUE THREAD

**Issue by reny-pacheco** [Aman-Mandal/groovy#76]
### Make the cursor to pointer when hovering the **Groovy** title in sidebar.
In my own opinion, since it is a link, it's much better to change the cursor to pointer.

Screenshot:
![image](https://user-images.githubusercontent.com/64537418/194584560-f6f850e4-9bff-48bb-82b2-4d0dd7d49958.png)

**Comment by reny-pacheco** [comment]
Hi there, If this is a valid issue, I would like to work on this. Please assign this to me. Thank you

**Comment by Aman-Mandal** [comment]
> Hi there, If this is a valid issue, I would like to work on this. Please assign this to me. Thank you

Go ahead Sir

**Comment by Aman-Mandal** [comment]
#77 PR merged!!
