### ISSUE TITLE
implement search functionality

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#8]

**Comment by nidhi333-9** [comment]
@Aadarsh805 Hey there! I would like to work on this.

**Comment by Aman-Mandal** [comment]
> @Aadarsh805 Hey there! I would like to work on this.

Go ahead!! 😃

But for now we haven't connected this with API so there's nothing much to do, but you can change the state and other stuffs

**Comment by nidhi333-9** [comment]
Thanks, @Aman-Mandal  for assigning this to me :)

**Comment by Aadarsh805** [comment]
alright this is also done, will need to implement this with shazam API data only now
