### ISSUE TITLE
duplicate Albums label on sidebar

### ISSUE THREAD

**Issue by reny-pacheco** [Aman-Mandal/groovy#81]
Duplicate **Albums** label in sidebar.

Clicking either of the two highlights both.

Screenshot:

![image](https://user-images.githubusercontent.com/64537418/194601060-d49378b5-ad73-4517-b330-b4dad3f67d5a.png)

**Comment by reny-pacheco** [comment]
Hi there, if this is a valid issue, I would like to work on this. Thank you

**Comment by Aman-Mandal** [comment]
> Hi there, if this is a valid issue, I would like to work on this. Thank you

Go ahead..remove it from one place
