### ISSUE TITLE
make a basic loader component to show when fetching data from api

### ISSUE THREAD

**Issue by Aadarsh805** [Aman-Mandal/groovy#88]

**Comment by racky7** [comment]
@Aadarsh805 Please assign it to me.

**Comment by Aadarsh805** [comment]
> @Aadarsh805 Please assign it to me.

assigned, go ahead

**Comment by racky7** [comment]
@Aadarsh805 Thanks! please provide the detail/route of the component.

**Comment by Aadarsh805** [comment]
@racky7 You can just make a component named Loader.jsx in components folder, we will import it in places wherever necessary

**Comment by Aadarsh805** [comment]
you can use react-loader library if u want or u can make custom

**Comment by racky7** [comment]
Sorry, I am unassigning myself.

**Comment by vinayak41** [comment]
Please assign it to me.

**Comment by Aman-Mandal** [comment]
> Please assign it to me.

Here u go Sir!! Good luck :)

**Comment by vinayak41** [comment]
Can i get a design for loader ?

**Comment by Aman-Mandal** [comment]
> Can i get a design for loader ?
> 

We don't have any particular design but you can make something similar to our UI.

Take reference from dribbble or other designing platforms

**Comment by vinayak41** [comment]
#99
