### ISSUE TITLE
Warning 'two children with the same key' on the top chart list.

### ISSUE THREAD

**Issue by ann0nip** [Aman-Mandal/groovy#97]
![Screen Shot 2022-10-09 at 09 28 12](https://user-images.githubusercontent.com/2248100/194756845-1b1f6dab-f03d-45a4-9c63-5b1b08af4487.png)

The map loop should use a unique key as props. The response has that; I will update that.

Please assign it to me.

**Comment by Aman-Mandal** [comment]
> ![Screen Shot 2022-10-09 at 09 28 12](https://user-images.githubusercontent.com/2248100/194756845-1b1f6dab-f03d-45a4-9c63-5b1b08af4487.png)
> 
> The map loop should use a unique key as props. The response has that; I will update that.
> 
> Please assign it to me.

Sure sir..go ahead!!
